config/routes.rb
Rails.application.routes.draw do
  # Devise authentication
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  # Static pages
  get "home", to: "pages#home"
  get "about", to: "pages#about"
  get "calendar", to: "pages#calendar"
  get "partners", to: "pages#partners"
  get "sponsors", to: "pages#sponsors"
  get "amanah_house", to: "pages#amanah_house"
  get "media_mentions", to: "pages#media_mentions"
  get "leaders", to: "pages#leaders"
  root "pages#home"

  # User-specific routes
  get "/my_registrations", to: "registrations#my_registrations", as: "my_registrations"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :testimonials, only: [ :index, :new, :create ]

  concern :registrable do
    resources :registrations, only: [ :create ]
    resources :payments, only: [ :create ]
  end

  resources :activities, param: :slug, concerns: :registrable
  resources :trips, param: :slug, concerns: :registrable

  # Membership payments (handled at the top level)
  resources :payments, only: [ :create ] do
    collection do
      post :cancel_subscription
    end
  end

  get "/payments/success", to: "payments#success"
  get "/payments/cancel", to: "payments#cancel"
end

app/views/layouts/_footer.html.erb
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top footer-custom flex-column flex-md-row text-center text-md-start">
  <div class="col-md-4 d-flex align-items-center ms-md-3 mb-2 mb-md-0">
    <span>© 2025 Amanah Recreational Project</span>
  </div>
  <div class="d-flex align-items-center justify-content-center mb-2 mb-md-0">
    <i class="fa-solid fa-envelope me-2"></i>
    <a href="mailto:info@amanahrec.org">info@amanahrec.org</a>
  </div>
  <div class="mb-2 mb-md-0 text-center">
    <% if user_signed_in? %>
      <%= button_to "Become a Member!", 
                payments_path(paymentable_type: "Membership", paymentable_id: current_user.id), 
                method: :post, 
                class: "btn become-member", data: { turbo: false } %>
    <% else %>
      <%= link_to "Become a Member!", new_user_session_path, class: "btn become-member" %>
    <% end %>
  </div>
  <ul class="nav col-md-4 justify-content-center justify-content-md-end list-unstyled d-flex">
    <li class="me-2">Follow us:</li>
    <li class="mx-2"><a href="https://www.instagram.com/amanahrec/" role="button">
        <i class="fab fa-instagram fa-lg"></i>
      </a></li>
    <li class="mx-2"><a href="https://www.facebook.com/profile.php?id=61550329167641" role="button">
        <i class="fab fa-facebook-f fa-lg"></i>
      </a></li>
    <li class="mx-2"><a href="https://www.tiktok.com/@amanahrec" role="button">
        <i class="fab fa-tiktok fa-lg"></i>
      </a></li>
  </ul>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-xl">
  <div class="container-fluid justify-content-between">
    <a class="navbar-brand" href="<%= root_path %>">
      <img src="/AmanahRecProject3_Final.png" alt="Amanah Rec Logo">
      <span class="navbar-brand">Amanah Rec</span>
    </a>
    <div class="d-flex ms-auto">
      <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navigation Links -->
      <ul class="navbar-nav lead d-flex align-items-center mx-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="aboutDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            About
          </a>
          <ul class="dropdown-menu" aria-labelledby="aboutDropdown">
            <li><%= link_to "About Us", about_path, class: "dropdown-item" %></li>
            <li><%= link_to "Our Board & Team", leaders_path, class: "dropdown-item" %></li>
            <li><%= link_to "Our Partners", partners_path, class: "dropdown-item" %></li>
            <li><%= link_to "Our Sponsors", sponsors_path, class: "dropdown-item" %></li>
            <li><%= link_to "Amanah House", amanah_house_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item"><%= link_to "Activities & Events", activities_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Trips", trips_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Calendar", calendar_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Latest News", media_mentions_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Eco Jariyah", "https://www.ecojariyah.com/", class: "nav-link", target: "_blank" %></li>
        <li class="nav-item"><%= link_to "Donate", "https://www.launchgood.com/v4/pledge/hiking_hijabie_programs", class: "nav-link", id: "donate" %></li>
      </ul>
      <!-- User Links -->
      <ul class="navbar-nav lead d-flex align-items-center ms-auto ">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-user"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li class="dropdown-header">
                Hi, <%= current_user.first_name %>!
              </li>
              <li class="nav-item"><%= link_to "My Registrations", my_registrations_path, class: "dropdown-item " %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item " %></li>
              <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item " %></li>
              <% if current_user.membership&.active? %>
                <!-- Active Subscription -->
                <li class="dropdown-item ">
                  <span class="btn btn-outline-success btn-sm" style="pointer-trips: none; opacity: 0.65; cursor: default;">
                    Active <i class="fas fa-gem"></i>
                  </span>
                </li>
                <%= button_to 'Cancel Subscription', cancel_subscription_payments_path, 
                method: :post, class: "custom-danger-btn", data: { turbo: false } %>
              <% else %>
                <!-- Inactive Subscription -->
                <li class="dropdown-item">
                  <button class="btn btn-outline-secondary d-inline" disabled>Inactive <i class="fa-regular fa-gem"></i></button>
                </li>
              <% end %>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Amanah Rec Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <%= favicon_link_tag '/AmanahRecProject3_Final.png' %>
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.0/css/all.min.css" rel="stylesheet">
    <!-- Javscript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <body class="<%= 'devise-login-page' if devise_controller? %>">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key == "alert" ? "danger" : "success" %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= render 'layouts/navbar' %>
      <div class="container-fluid">
        <%= yield %> <!-- Main content area -->
      </div>
      <%= yield :javascript %>
      <%= render 'layouts/footer' %>
    </body>
  </html>